//
// Created by Auro on 29-01-2021.
//

#ifndef INDOOR_POSITIONING_SYSTEM_RSSITODISTANCE_H
#define INDOOR_POSITIONING_SYSTEM_RSSITODISTANCE_H


class RssiToDistance {

};


#endif //INDOOR_POSITIONING_SYSTEM_RSSITODISTANCE_H
